export const SLOTS = [
  [undefined, undefined, undefined, undefined, 'Event 5'],
  ['Event 1', undefined, undefined, undefined, 'Event 5'],
  ['Event 1', 'Event 2', undefined, 'Event 4', 'Event 5'],
  ['Event 1', 'Event 2', 'Event 3', 'Event 4', 'Event 5'],
  ['Event 1', 'Event 2', 'Event 3', 'Event 4', 'Event 5'],
  ['Event 1', 'Event 2', 'Event 3', undefined, undefined],
  [undefined, 'Event 2', 'Event 3', undefined, undefined],
  [undefined, undefined, 'Event 3', undefined, undefined],
  [undefined, undefined, 'Event 3', undefined, undefined],
  [undefined, undefined, 'Event 3', undefined, undefined],
  [undefined, undefined, undefined, undefined, undefined],
  [undefined, undefined, undefined, undefined, undefined],
  [undefined, undefined, undefined, undefined, undefined],
  [undefined, undefined, undefined, undefined, undefined],
  [undefined, undefined, undefined, undefined, undefined],
  [undefined, undefined, undefined, undefined, undefined],
  [undefined, undefined, undefined, undefined, undefined],
  [undefined, undefined, undefined, undefined, undefined],
  [undefined, undefined, undefined, undefined, undefined],
  [undefined, undefined, undefined, undefined, undefined],
  [undefined, undefined, undefined, undefined, undefined],
  [undefined, undefined, undefined, undefined, undefined],
  [undefined, undefined, undefined, undefined, undefined],
  [undefined, undefined, undefined, undefined, undefined],
  [undefined, undefined, undefined, undefined, undefined],
  [undefined, undefined, undefined, undefined, undefined],
  [undefined, undefined, undefined, undefined, undefined],
  [undefined, undefined, undefined, undefined, undefined],
];
